/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_qwen_Qwen */

#ifndef _Included_io_github_qwen_Qwen
#define _Included_io_github_qwen_Qwen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_qwen_Qwen
 * Method:    generate
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_qwen_Qwen_generate
  (JNIEnv *, jobject, jstring, jobject );

/*
 * Class:     io_github_qwen_Qwen
 * Method:    load
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_qwen_Qwen_load
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     io_github_qwen_Qwen
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_qwen_Qwen_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
